/* becode/eslint-config
 *
 * /index.js - ESLint shared configuration
 *
 * coded by leny@BeCode
 * started at 25/02/2019
 */

const WARNING = 1;
const ERROR = 2;

module.exports = {
    env: {
        browser: true,
        node: true,
        es6: true,
    },
    parser: "babel-eslint",
    parserOptions: {
        ecmaVersion: 2019,
        sourceType: "module",
        ecmaFeatures: {
            jsx: true,
        },
    },
    plugins: ["prettier", "react", "unicorn"],
    settings: {
        react: {
            version: "16.8",
        },
    },
    rules: {
        // Possible Errors
        "for-direction": ERROR,
        "getter-return": ERROR,
        "no-async-promise-executor": ERROR,
        "no-await-in-loop": ERROR,
        "no-compare-neg-zero": ERROR,
        "no-cond-assign": [ERROR, "except-parens"],
        "no-console": [WARNING],
        "no-constant-condition": ERROR,
        "no-control-regex": ERROR,
        "no-debugger": WARNING,
        "no-dupe-args": ERROR,
        "no-dupe-keys": ERROR,
        "no-duplicate-case": ERROR,
        "no-empty": ERROR,
        "no-empty-character-class": ERROR,
        "no-ex-assign": ERROR,
        "no-extra-boolean-cast": ERROR,
        "no-extra-parens": [
            ERROR,
            "all",
            {
                ignoreJSX: "all",
                enforceForArrowConditionals: false,
                nestedBinaryExpressions: false,
            },
        ],
        "no-extra-semi": ERROR,
        "no-func-assign": ERROR,
        "no-inner-declarations": ERROR,
        "no-invalid-regexp": ERROR,
        "no-irregular-whitespace": ERROR,
        "no-misleading-character-class": ERROR,
        "no-obj-calls": ERROR,
        "no-prototype-builtins": ERROR,
        "no-regex-spaces": ERROR,
        "no-sparse-arrays": ERROR,
        "no-template-curly-in-string": ERROR,
        "no-unexpected-multiline": ERROR,
        "no-unreachable": ERROR,
        "no-unsafe-finally": ERROR,
        "no-unsafe-negation": ERROR,
        "require-atomic-updates": ERROR,
        "use-isnan": ERROR,
        "valid-typeof": ERROR,

        // Best Practices
        "accessor-pairs": [ERROR],
        "array-callback-return": ERROR,
        "block-scoped-var": WARNING,
        "class-methods-use-this": WARNING,
        "consistent-return": ERROR,
        curly: [ERROR, "all"],
        "default-case": ERROR,
        "dot-notation": ERROR,
        eqeqeq: [ERROR, "smart"],
        "guard-for-in": ERROR,
        "max-classes-per-file": ERROR,
        "no-alert": ERROR,
        "no-caller": ERROR,
        "no-case-declarations": ERROR,
        "no-div-regex": ERROR,
        "no-else-return": ERROR,
        "no-empty-function": ERROR,
        "no-empty-pattern": ERROR,
        "no-eval": ERROR,
        "no-extend-native": ERROR,
        "no-extra-bind": ERROR,
        "no-extra-label": ERROR,
        "no-fallthrough": ERROR,
        "no-floating-decimal": ERROR,
        "no-global-assign": ERROR,
        "no-implicit-globals": ERROR,
        "no-implied-eval": ERROR,
        "no-invalid-this": ERROR,
        "no-iterator": ERROR,
        "no-labels": ERROR,
        "no-lone-blocks": ERROR,
        "no-loop-func": ERROR,
        "no-multi-spaces": ERROR,
        "no-multi-str": ERROR,
        "no-new": ERROR,
        "no-new-func": ERROR,
        "no-new-wrappers": ERROR,
        "no-octal": ERROR,
        "no-octal-escape": ERROR,
        "no-param-reassign": ERROR,
        "no-proto": ERROR,
        "no-redeclare": ERROR,
        "no-return-assign": [ERROR, "except-parens"],
        "no-return-await": ERROR,
        "no-script-url": ERROR,
        "no-self-assign": ERROR,
        "no-self-compare": ERROR,
        "no-sequences": ERROR,
        "no-throw-literal": ERROR,
        "no-unmodified-loop-condition": ERROR,
        "no-unused-expressions": [ERROR, {allowShortCircuit: true}],
        "no-useless-call": ERROR,
        "no-useless-catch": ERROR,
        "no-useless-concat": ERROR,
        "no-useless-escape": ERROR,
        "no-useless-return": ERROR,
        "no-with": ERROR,
        "prefer-promise-reject-errors": ERROR,
        radix: [ERROR, "as-needed"],
        "require-await": ERROR,

        // Variables
        "no-delete-var": ERROR,
        "no-label-var": ERROR,
        "no-shadow": ERROR,
        "no-shadow-restricted-names": ERROR,
        "no-undef": ERROR,
        "no-undef-init": ERROR,
        "no-undefined": ERROR,
        "no-unused-vars": [ERROR, {args: "after-used"}],
        "no-use-before-define": ERROR,

        // Node.js and CommonJS
        "global-require": ERROR,
        "no-buffer-constructor": ERROR,
        "no-mixed-requires": WARNING,
        "no-new-require": ERROR,
        "no-path-concat": ERROR,
        "no-sync": WARNING,

        // ECMAScript 6
        "arrow-body-style": [ERROR, "as-needed"],
        "arrow-parens": [ERROR, "as-needed"],
        "arrow-spacing": ERROR,
        "constructor-super": ERROR,
        "generator-star-spacing": ERROR,
        "no-class-assign": ERROR,
        "no-confusing-arrow": [ERROR, {allowParens: true}],
        "no-const-assign": ERROR,
        "no-dupe-class-members": ERROR,
        "no-duplicate-imports": ERROR,
        "no-new-symbol": ERROR,
        "no-this-before-super": ERROR,
        "no-useless-computed-key": ERROR,
        "no-useless-constructor": ERROR,
        "no-useless-rename": ERROR,
        "no-var": ERROR,
        "object-shorthand": WARNING,
        "prefer-arrow-callback": WARNING,
        "prefer-const": WARNING,
        "prefer-rest-params": ERROR,
        "prefer-spread": ERROR,
        "prefer-template": ERROR,
        "require-yield": ERROR,
        "rest-spread-spacing": [ERROR, "never"],
        "symbol-description": ERROR,

        // Prettier
        "prettier/prettier": [
            ERROR,
            {
                singleQuote: false,
                tabWidth: 4,
                trailingComma: "all",
                arrowParens: "avoid",
                bracketSpacing: false,
                jsxBracketSameLine: true,
            },
        ],

        // React
        "react/button-has-type": WARNING,
        "react/no-access-state-in-setstate": WARNING,
        "react/no-array-index-key": ERROR,
        "react/no-children-prop": ERROR,
        "react/no-danger": ERROR,
        "react/no-danger-with-children": ERROR,
        "react/no-deprecated": ERROR,
        "react/no-direct-mutation-state": ERROR,
        "react/no-find-dom-node": ERROR,
        "react/no-is-mounted": ERROR,
        "react/no-multi-comp": ERROR,
        "react/no-redundant-should-component-update": ERROR,
        "react/no-render-return-value": ERROR,
        "react/no-typos": ERROR,
        "react/no-string-refs": ERROR,
        "react/no-this-in-sfc": ERROR,
        "react/no-unescaped-entities": ERROR,
        "react/no-unknown-property": ERROR,
        "react/no-will-update-set-state": ERROR,
        "react/prefer-es6-class": ERROR,
        "react/react-in-jsx-scope": ERROR,
        "react/require-render-return": ERROR,
        "react/self-closing-comp": ERROR,
        "react/void-dom-elements-no-children": ERROR,

        // React:jsx
        "react/jsx-closing-bracket-location": [
            ERROR,
            {
                selfClosing: "tag-aligned",
                nonEmpty: "after-props",
            },
        ],
        "react/jsx-closing-tag-location": ERROR,
        "react/jsx-equals-spacing": ERROR,
        "react/jsx-first-prop-new-line": ERROR,
        "react/jsx-handler-names": ERROR,
        "react/jsx-key": ERROR,
        "react/jsx-max-depth": [WARNING, {max: 5}],
        "react/jsx-no-comment-textnodes": ERROR,
        "react/jsx-no-duplicate-props": ERROR,
        "react/jsx-no-literals": ERROR,
        "react/jsx-no-target-blank": ERROR,
        "react/jsx-no-undef": ERROR,
        "react/jsx-curly-brace-presence": [
            ERROR,
            {props: "always", children: "ignore"},
        ],
        "react/jsx-pascal-case": ERROR,
        "react/jsx-props-no-multi-spaces": ERROR,
        "react/jsx-tag-spacing": [
            ERROR,
            {beforeSelfClosing: "always", beforeClosing: "never"},
        ],
        "react/jsx-uses-react": ERROR,
        "react/jsx-uses-vars": ERROR,
        "react/jsx-wrap-multilines": [
            ERROR,
            {
                declaration: "parens-new-line",
                assignment: "parens-new-line",
                return: "parens-new-line",
                arrow: "parens",
                condition: "parens",
                logical: "parens",
                prop: "parens",
            },
        ],

        // Unicorn: additional rules
        "unicorn/error-message": ERROR,
        "unicorn/filename-case": [ERROR, {case: "kebabCase"}],
        "unicorn/new-for-builtins": ERROR,
        "unicorn/no-abusive-eslint-disable": WARNING,
        "unicorn/no-array-instanceof": ERROR,
        "unicorn/no-for-loop": WARNING,
        "unicorn/prefer-includes": ERROR,
        "unicorn/prefer-query-selector": ERROR,
        "unicorn/throw-new-error": ERROR,
    },
};
